name: Opening process of the PR

on:
  pull_request:
    branches: [ develop ]
    types: [ opened ]

jobs:
  save-snapshot:

    runs-on: ubuntu-latest
    if: ${{ startsWith(github.head_ref, 'feature/') }}

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Attach HEAD
      run: git checkout ${{ github.base_ref }}

    - name: Create snapshot
      shell: bash
      run: |
        branch=${{ github.head_ref }}
        snapshot=ss-from${branch#feature}
        [ -n "$(git branch -r | sed 's/ //g' | grep -e ^origin/$snapshot)" ] && git push origin $snapshot --delete
        git checkout -b $snapshot
        git push origin $snapshot