name: publish
on: 
  workflow_dispatch:
    inputs:
      version: 
        description: 'package version.'
        required: true
        type: string
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set git configs
      run: |
        git config --global user.email "begyyal@gmail.com"
        git config --global user.name "begyyal-ghost"
    - name: Push a git tag
      run: |
        git tag ${{ inputs.version }}
        git push origin ${{ inputs.version }} -f
    - name: Post tweet
      run: |
        ./tool/tweet_template.sh \
        ${{ inputs.version }} \
        ${{ github.event.repository.html_url }} > ./data_temp
        ./tool/tweet.sh \
        ${{ secrets.TW_CONS_KEY }} \
        ${{ secrets.TW_CONS_SECRET }} \
        ${{ secrets.TW_OAUTH_TOKEN }} \
        ${{ secrets.TW_OAUTH_SECRET }} \
        ./data_temp

