name: sync-pr

on:
  workflow_dispatch: 
  pull_request:
    branches: [ stg ]
    types: [ opened, synchronize ]

jobs:

  pr-update-process:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    - name: Prepare conditions
      id: cond1
      if: ${{ github.event.action == 'opened' }}
      run: |
        [ ${{ github.event_name == 'dispatch' }} == true ] && do_test=true || \
        git checkout ${{ github.base_ref }}
        git checkout ${{ github.head_ref }}
        do_test=$(./.github/workflows/sh/check_if_need_test.sh ${{ github.base_ref }} ${{ github.head_ref }})
        echo "do-test=${do_test:-false}" >> $GITHUB_OUTPUT

    - name: Prepare conditions
      id: cond2
      if: ${{ github.event.action == 'synchronize' }}
      run: |
        [ ${{ github.event_name == 'dispatch' }} == true ] && do_test=true || \
        do_test=$(./.github/workflows/sh/check_if_need_test.sh ${{ github.event.before }} ${{ github.event.after }})
        echo "do-test=${do_test:-false}" >> $GITHUB_OUTPUT

    - name: Set up JDK 15
      if: ${{ steps.cond1.outputs.do-test == 'true' || steps.cond2.outputs.do-test == 'true' }}
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'

    - name: Build with Gradle
      if: ${{ steps.cond1.outputs.do-test == 'true' || steps.cond2.outputs.do-test == 'true' }}
      run: |
        chmod +x ./cmd/gradlew
        ./cmd/gradlew build -b ./lib/build.gradle
        ./cmd/gradlew build -b ./cmd/build.gradle

    - name: Test
      if: ${{ steps.cond1.outputs.do-test == 'true' || steps.cond2.outputs.do-test == 'true' }}
      run: ./test.sh

    - name: Mark success of status checks
      run: |
        curl \
          -X POST \
          -H "AUTHORIZATION: token ${{ github.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
          -d '{"state":"success","context":"ci-passed-stg"}'
