name: Update process of the PR

on:
  pull_request:
    branches: [ develop ]
    types: [ synchronize ]

jobs:
  save-snapshot:

    runs-on: ubuntu-latest
    if: ${{ startsWith(github.head_ref, 'feature/') }}

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Attach HEAD
      run: git checkout ${{ github.head_ref }}

    - name: Create snapshot
      shell: bash
      run: |
        branch=${{ github.head_ref }}
        snapshot=ss-to${branch#feature}
        [ -n "$(git branch -r | sed 's/ //g' | grep -e ^origin/$snapshot)" ] && git push origin $snapshot --delete
        git checkout -b $snapshot
        git push origin $snapshot

  build-and-test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: Set git configs
      run: |
        git config --global user.email "begyyal@gmail.com"
        git config --global user.name "begyyal-ghost"

    - name: Update submodules
      run: git submodule update --remote

    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Test
      run: ./test.sh
