name: Update process of the PR

on:
  pull_request:
    branches: [ develop ]
    types: [ opened, synchronize ]

jobs:
  sync-pr:

    runs-on: ubuntu-latest
    if: ${{ startsWith(github.head_ref, 'feature/') }}

    steps:

    - name: Extract the issue no
      id: ready
      shell: bash
      run: |
        branch=${{github.head_ref}}
        echo "::set-output name=issue-no::${branch#feature/}"

    - name: Clone repo
      shell: bash
      run: git clone https://github.com/begyyal/act_revise_comments.git

    - name: Revise target feature's comments
      uses: ./act_revise_comments
      with:
        issueNo: ${{ steps.ready.outputs.issue-no }}
