name: Save snapshot of PR

on:
  pull_request:
    branches: [ develop ]
    types: [ opened, synchronize ]

jobs:
  save-snapshot:

    runs-on: ubuntu-latest
    if: ${{ startsWith(github.head_ref, 'feature/') }}

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Create snapshot-from
      shell: bash
      run: |
        branch=${{ github.head_ref }}
        snapshot=ss-from${branch#feature}
        [ -n "$(git branch -r | sed 's/ //g' | grep -e ^origin/$snapshot)" ] && git push origin $snapshot --delete
        git checkout ${{ github.base_ref }}
        git checkout -b $snapshot
        git push origin $snapshot

    - name: Create snapshot-to
      shell: bash
      run: |
        branch=${{ github.head_ref }}
        snapshot=ss-to${branch#feature}
        [ -n "$(git branch -r | sed 's/ //g' | grep -e ^origin/$snapshot)" ] && git push origin $snapshot --delete
        git checkout ${{ github.head_ref }}
        git checkout -b $snapshot
        git push origin $snapshot
